### PR TITLE
Added row coloring (striping) to table rows.

### PR DESCRIPTION
**Pull request by tedyoung**
I added alternate row striping to the tables to make it easier to scan across the whitespace gap between columns.

### CODE REVIEW

**Comment by jfhbrook** [comment]
This sounds cool. I'll have to take a closer look...

**Comment by tedyoung** [comment]
I only tested this with writeLaTex, so let me know if I messed up anything: https://www.writelatex.com/145300dvtxfz

**Comment by jfhbrook** [comment]
Looks really nice in writeLaTeX! I'll let you know if I run into anything I can't fix when I pull this in.

**Comment by juliangruber** [comment]
looks good, yes!

**Comment by jfhbrook** [comment]
Very cool. I pulled this in here https://github.com/bigcompany/know-your-http/commit/12b8652d41b0fcc468d1cae256c553349006e731 and also added striping to the other two posters.

Thanks a bunch!

**Pull request closed without merging**
